# Generated by Django 2.0 on 2018-01-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('unique_token', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
