# Generated by Django 2.0 on 2018-01-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
