# Generated by Django 2.0 on 2018-01-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('app', '0004_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='token',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
